### DISCUSSION TITLE
Nuxt.js on Google App Engine Standard Environment

### DISCUSSION THREAD

**Discussion by dvdbrk** [nuxt/nuxt#10207] [Questions (Nuxt 2)]
I am serving Nuxt.js SSR application from Google App Engine, from F2 instance. All is deployed ok and works well, but sometimes I hit a weird 500 server error. I think the problem is because GAE shuts down my instance because it is rarely used. When the instance is created again, my website fails to load (timeouts), resulting in 500 error. I am using serverMiddleware with Express.

**/server/middleware.js**
```
const express = require('express')
const app = express()

// this fetches a CMS token and creates a CMS object used in the request below
const CMS = require('../cms')

app.use(express.json())
app.use(express.urlencoded({ extended: true }))

// get Page from the CMS
app.post('/page', async (req, res, next) => {

    try {
        let result = await CMS.getPage(req.body.route)
        res.status(200).json(result)

    } catch (error) {
        console.log('Error', error)
    
   }
})
```

**app.yaml**
```
runtime: nodejs12
instance_class: F2

handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    secure: always

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  HOST: "0.0.0.0"
  NODE_ENV: "production"

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_instances: 1
  max_instances: 1
  target_cpu_utilization: 0.9
  target_throughput_utilization: 0.9
  max_concurrent_requests: 50
```

**Log image**
[https://i.stack.imgur.com/qvHIh.png](https://i.stack.imgur.com/qvHIh.png)

**Error expanded**
```
0: {
  logMessage: "Request was aborted after waiting too long to attempt to service your request."
  severity: "ERROR"
  time: "2022-01-14T08:55:22.057499Z"
}
```

Am I doing something wrong here? I would not mind keeping the costs down and scaling back to 0 instances when they are not needed, but the website would still need to be served as fast as possible.
