### DISCUSSION TITLE
how to get env from docker container in nuxtjs?

### DISCUSSION THREAD

**Discussion by coaperator** [nuxt/nuxt#10347] [Questions (Nuxt 2)]
Compiled an image with a frontend on nuxtjs
run in docker-compose
```
version: '3.5'

services:
  frontend:
    container_name: mc-frontend
    image: registry.gitlab.com/path/develop:latest
    env_file: .env
    ports:
      - 3000:3000
    restart: always
```
.env has different values ​​depending on the server running the container

```
const apiUrl = process.env.API_URL || 'localhost'

const apolloConf = {
  clientConfigs: {
    default: {
      httpEndpoint: apiUrl,
      prefetch: false,
    },
  },
}

export default {
  server: {
    port: 3000, // default: 3000
  },

 ...

  publicRuntimeConfig: {
    gapiUrl,
  },

  apollo: apolloConf,
}
```

variables from the .env file come to the container, but nuxjs does not see them, I tried to get them like this instruction https://nuxtjs.org/tutorials/moving-from-nuxtjs-dotenv-to-runtime-config/
