### DISCUSSION TITLE
GitLab Pipeline Service for Cypress Testing

### DISCUSSION THREAD

**Discussion by nadar** [nuxt/nuxt#10836] [Questions (Nuxt 2)]
We have now spent days on getting a working nuxt docker image running as service in gitlab in order to make e2e tests with cypress, without any success. Googling, Searching Issues, Testing things, no luck :-( So i try to report here, maybe something has an idea:

The main problem is `yarn start` (which does `nuxt start`) never runs correctly in a gitlab pipline and i would be interest if someone out there got `nuxt start` running successful in a gitlab pipline (in any context actually).

Here we have a very basic example of the gitlab-ci.yml

```
e2e
  image: 
    name: cypress/included:11.2.0
    entrypoint: [""]
  variables:
    CI_DEBUG_SERVICES: "true"
    PORT: 3043
  services: 
    - name: $CI_REGISTRY_IMAGE:e2etest
      command: ["yarn", "start"]
      alias: app
  script:
    - curl http://app:3043
 ```

+ the nuxt dockerfile is generated previously, the port can be assigned and adjusted with ENV var, in this case we take a random port 3043
+ i will link the dockerfile below
+ we can adjust command also by adding `["yarn", "start", "--port 3043"]` to ensure nuxt starts on this port, but the dockerfile exposes the port based on the `PORT`env var.

The curl command running in `script` always returns

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /</pre>
</body>
</html>
```

If i test the dockerfile locally, doing the same. It would return the generated "index.html" from nuxt.

The gitlab service logs outputs

```
Service container logs:
yarn run v1.22.19
$ nuxt start
```

its a `ssr` false project, but target is `server`. 

<details>
<summary>Dockerfile</summary>

```Dockerfile
FROM node:18-alpine AS BUILDSTAGE

## ARGS
ARG NODE_ENV=prod
## ENV
ENV NODE_OPTIONS=--openssl-legacy-provider
## WORKDIR & COPY
WORKDIR /app
COPY ./ /app
## RUN
RUN yarn install && yarn build

########### ==> NEXT STAGE: RUN FROM BUILD

FROM node:18-alpine
## ENV
ENV PORT=80
ENV NODE_OPTIONS=--openssl-legacy-provider
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=$PORT
## WORKDIR & COPY
WORKDIR /app
ADD package.json ./
ADD nuxt.config.js ./
COPY --from=BUILDSTAGE ./app/node_modules ./node_modules/
COPY --from=BUILDSTAGE ./app/.nuxt ./.nuxt/
COPY --from=BUILDSTAGE ./app/static ./static/
## RUN
RUN apk --no-cache add curl 
## EXPOSE
EXPOSE $PORT
## HEALTHCHECK
HEALTHCHECK --interval=30s --timeout=5s CMD curl --fail "http://localhost:$PORT" || exit 1
## COMMAND
CMD ["yarn", "start"]
```

</details>
