### DISCUSSION TITLE
How to add environment variables to node server after build?

### DISCUSSION THREAD

**Discussion by NK0D1NG** [nuxt/nuxt#16212] [Questions]
Hey,

we developed a Nuxt 3 App which uses environment variables like:
```
...
await $fetch(config.baseURL + req.path)
...
```

The baseURL is defined inside the nuxt.config.ts:
```
// https://v3.nuxtjs.org/api/configuration/nuxt.config
// https://pinia.vuejs.org/ssr/nuxt.html

export default defineNuxtConfig({
    modules: [
       
    ],
    buildModules: [
        
    ],
    runtimeConfig: {
        public: {
          baseURL: process.env.API_BASE_URL,
        }
      }
  })

```

And the .env:
```
....
API_BASE_URL=http://localhost
....
```

which works fine for local development. Now we are building the app for SSR (hosting with a NodeJS Server). The question now is:
How can we tell the nodeJS server about the environment variable? I built a simple docker image which has all the code from the .output-folder after running `npm run build` and using a simple entrypoint to start the server:

Dockerfile:
```
FROM node:18-alpine

WORKDIR /app

COPY .output/ .

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

EXPOSE 3000 

ENTRYPOINT ["node", "server/index.mjs"]
```

Now I am spinning up that docker container with docker-compose:
```
version: '3'
services:
    fe:
        image: my.registry.com/my-project/my-app/node:latest
        environment:
            - API_BASE_URL=https://my.backend..com
            - NUXT_PORT=3000
```

And if I inspect the container I see the overridden variable:
![grafik](https://user-images.githubusercontent.com/88783636/205655548-a91007a5-4a74-4f33-83d5-9675efe63aa7.png)

But using `process.env.API_BASE_URL` in the code (which is executed on the NodeJS server) always returns undefined - so the env variable does not seem to be processed/read by Nuxt on the server-side?

**Comment by TheAlexLichter** [comment]
Be aware that your `.env` file is **not taken into account** when starting the server. You can use `source .env && nuxt start` for example or pass variables via docker environment.

Also be aware that you need to use the `NUXT_` prefix, e.g. `NUXT_SOME_ENV_VARIABLE` instead of `SOME_ENV_VARIABLE`

**Reply by NK0D1NG** [reply]
Hey @manniL 
thank you for your response. Because the .env is not taken into account I decided to add an environment variable with the docker-compose.yml which seems to work (see the image I posted from the inspected container).

I did not find anything about the `NUXT`-prefix in the current Nuxt 3 docs so I was not sure if that's still needed. Also using it without the prefix in the local development mode is working? Do I need to add the prefix to the `nuxt.config.ts`, too?

So:
```
// https://v3.nuxtjs.org/api/configuration/nuxt.config
// https://pinia.vuejs.org/ssr/nuxt.html

export default defineNuxtConfig({
    modules: [
       
    ],
    buildModules: [
        
    ],
    runtimeConfig: {
        public: {
          baseURL: process.env.NUXT_API_BASE_URL,
        }
      }
  })

```

And then in the .env:
```
....
NUXT_API_BASE_URL=http://localhost
....
```

And later in the deployment of the node-server in the docker-compose:
```
version: '3'
services:
    fe:
        image: my.registry.com/my-project/my-app/node:latest
        environment:
            - NUXT_API_BASE_URL=https://my.backend..com
            - NUXT_PORT=3000
```
?
