### DISCUSSION TITLE
Nuxt 3 — Obfuscate/minify css selectors

### DISCUSSION THREAD

**Discussion by Illuday** [nuxt/nuxt#16255] [Questions]
Hey everyone,

I'm trying to replace all my css selector with minified names, on build, like this:

```css
.test {
    color: red;
}

to 

.a {
    color: red;
}
```

I'm working with scss, and lots of generated classes, I tried something with a postcss plugin, but it doesn't work. Have you any idea of what we could do to manage this?

Thanks
