### DISCUSSION TITLE
Google App Engine Deployment

### DISCUSSION THREAD

**Discussion by SleepiestAdam** [nuxt/nuxt#16545] [Questions]
Had anyone managed to get a Nuxt 3 build deployed to Google App Engine?

While I can get the .output directory uploaded; I'm just getting a 500 error back when trying to run the app. I'm thinking my app.yaml file isn't setup correctly (this is my first time deploying a nodejs app so very likely I've screwed up in terms of entrpoint and handlers etc).

I was wondering if anyone had any success getting it uploaded to GAE / has an app.yaml contents they can share that's setup correctly?

```
runtime: nodejs16
instance_class: F2

entrypoint: node server/index.mjs

handlers:
  - url: /img
    static_dir: public/img

  - url: /fonts
    static_dir: public/fonts

  - url: /css
    static_dir: public/css

  - url: /_nuxt
    static_dir: public/_nuxt

  - url: /.*
    secure: always
    script: auto

env_variables:
  HOST: '0.0.0.0'
```

Many thanks!

**Comment by arb85** [comment]
Check GAE logs for all the information of the 500 error, maybe it's about some missing dependencies.

I’ve tested Nuxt3 before RC with deployment on GAE, I'll post here my app.yaml configuration in a while.

**Comment by arb85** [comment]
> Here my **app.yaml**
```yaml
runtime: nodejs16

instance_class: F2

entrypoint: node .output/server/index.mjs

# handlers:
#   - url: /_nuxt
#     static_dir: .nuxt/dist/client
#     secure: always

#   - url: /(.*\.(gif|png|jpg|ico|txt))$
#     static_files: static/\1
#     upload: static/.*\.(gif|png|jpg|ico|txt)$
#     secure: always

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  NUXT_HOST: '0.0.0.0'
  NUXT_PORT: '8080'
  NODE_ENV: 'production'
```

But with Nuxt3 version ^3.0.0-27375427.d07d572
i also had to manually install these dependencies
> **package.json**
``` json
{
    ...
  "dependencies": {
    "destr": "^1.1.0",
    "h3": "^0.3.9",
    "ohmyfetch": "^0.4.15",
    "pathe": "^0.2.0",
    "unenv": "^0.4.3"
  }
}
```

so you can try with:

``` bash
npm i destr h3 ohmyfetch pathe unenv
```

**Comment by SleepiestAdam** [comment]
@arb85 - thanks for the help, unfortunately still getting the following build error and not really what to try 😅:

```
File upload done.
Updating service [default]...failed.                                                                                                          
ERROR: (gcloud.app.deploy) Error Response: [9] Cloud build 58416afc-34b5-400d-a769-3bbff9ace627 status: FAILURE
> postinstall
> nuxt prepare

/tmp/postinstall-21c27648.sh: 1: /tmp/postinstall-21c27648.sh: nuxt: not found
npm ERR! code 127
npm ERR! path /workspace
npm ERR! command failed
npm ERR! command sh /tmp/postinstall-21c27648.sh
```

**Reply by arb85** [reply]
Could You post here your ```package.json``` file?
Also just _dependencies_ and _devDependencies_

**Reply by SleepiestAdam** [reply]
Hey @arb85 sure thing!

(And thanks very much for the help on this / you're a life saver 😅!)

```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxtjs/google-fonts": "^3.0.0-0",
    "@tailwindcss/aspect-ratio": "^0.4.2",
    "@tailwindcss/line-clamp": "^0.4.2",
    "nuxt": "^3.0.0-rc.12",
    "tailwindcss": "^3.1.8",
    "vue-stripe-js": "^1.0.1"
  },
  "dependencies": {
    "@headlessui/vue": "^1.7.2",
    "@nuxt-hero-icons/outline": "^1.0.1",
    "@nuxt-hero-icons/solid": "^1.0.1",
    "@pinia/nuxt": "^0.4.3",
    "@stripe/stripe-js": "^1.36.0",
    "amplitude-js": "^8.21.0",
    "destr": "^1.1.1",
    "h3": "^0.3.9",
    "liquidjs": "^9.42.0",
    "lottie-web": "^5.9.6",
    "ohmyfetch": "^0.4.20",
    "pathe": "^0.2.0",
    "swiper": "^8.4.2",
    "unenv": "^0.4.6",
    "v-lazy-image": "^2.1.1",
    "vue-qrcode": "^2.2.0",
    "vue3-google-login": "^2.0.12"
  }
}

```

**Reply by arb85** [reply]
You're welcome, just here trying to help!

I'm looking at my previous deployment, but since then, nuxi commands have changed.
Do you use any sort of GitHub Actions to deploy on GAE?

I used this strategy with Nuxt3 version ^3.0.0-27375427.d07d572:
> ```.github/workflows/main.yaml```

``` yaml
name: CI/CD to Google App Engine

on:
  # push:
  #   branches:
  #     - main
  #     - master
  pull_request:
    branches:
      - production
      # - main
      # - master

jobs:
  ci-cd:
    name: Build Nuxt and Deploy to Google Cloud
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Create .env file with GitHub Secrets 🔑
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_CATALOG_API: ${{secrets.CATALOG_API}}
          envkey_CUSTOMER_APP_TOKEN: ${{secrets.CUSTOMER_APP_TOKEN}}
          file_name: .env

      - name: Cache node_modules 📦
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies 👨🏻‍💻
        run: npm ci

      # - name: Run linter 👀
      #   run: npm run lint

      - name: Build 🛠
        run: npm run build

      - name: Deploy to App Engine 🚀
        id: Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          deliverables: app.yaml
          version: go-instore-menu
          credentials: ${{ secrets.GCP_CREDENTIALS}}

      - name: Test deploy 🔬
        run: curl "${{ steps.deploy.outputs.url }}"
```

**Reply by arb85** [reply]
Let's just try this to test:

move   ```"nuxt": "^3.0.0-rc.12"``` line

from ```devDependencies```
to ```dependencies```

in your ```package.json```

**Reply by arb85** [reply]
> @arb85 - thanks for the help, unfortunately still getting the following build error and not really what to try 😅:
> 
> ```
> File upload done.
> Updating service [default]...failed.                                                                                                          
> ERROR: (gcloud.app.deploy) Error Response: [9] Cloud build 58416afc-34b5-400d-a769-3bbff9ace627 status: FAILURE
> > postinstall
> > nuxt prepare
> 
> /tmp/postinstall-21c27648.sh: 1: /tmp/postinstall-21c27648.sh: nuxt: not found
> npm ERR! code 127
> npm ERR! path /workspace
> npm ERR! command failed
> npm ERR! command sh /tmp/postinstall-21c27648.sh
> ```

From this, it seems related to ```nuxi``` "prepare" command, I've checked here: https://github.com/nuxt/framework/blob/ac60d362c9af4185effc85c7f9b68ad494115956/packages/nuxi/src/commands/prepare.ts

try this before moving "nuxt" as suggested before:

``` bash
npm i consola @nuxt/kit
```

**Reply by SleepiestAdam** [reply]
So - some progress (I think!)... By moving:

```
    "nuxt": "^3.0.0-rc.12",
    "@nuxtjs/google-fonts": "^3.0.0-0",
```
Into dependencies rather than devDependencies - it now uploads successfully to GAE... However when trying to run the app it returns a 500 Server error, with the following error log:

```
{
  "textPayload": "SyntaxError: The requested module 'h3' does not provide an export named 'createEvent'\n    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)\n    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)\n    at async Promise.all (index 0)\n    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)\n    at async loadESM (node:internal/process/esm_loader:91:5)\n    at async handleMainPromise (node:internal/modules/run_main:65:12)",
  "insertId": "634fcb9d00082cfbbdb98ed6",
  "resource": {
    "type": "gae_app",
    "labels": {
      "project_id": "sleepiest-vue",
      "zone": "us15",
      "version_id": "1",
      "module_id": "default"
    }
  },
  "timestamp": "2022-10-19T10:04:13.535803Z",
  "severity": "ERROR",
  "labels": {
    "clone_id": "00c61b117c307a732e42ab06dfead5a67e9f428a8f2f7de69be6434c69aa170d1359410522bc8ed71718deb28d7da79f402be528295e898821c5"
  },
  "logName": "projects/sleepiest-vue/logs/stderr",
  "receiveTimestamp": "2022-10-19T10:04:13.776261431Z"
}

```

**Reply by arb85** [reply]
>   "textPayload": "SyntaxError: The requested module 'h3' does not provide an export named 'createEvent'

```createEvent``` is something related to some code of yours, maybe a function in a file in ```/server/api``` folder?

**Reply by SleepiestAdam** [reply]
Mmm so a "find in files" doesn't return anything for createEvent in the main project's code...

There are however createEvent functions in a number of the node modules folder's when I search the full project folder for "createEvent" in finder however:

ssr-window
swiper (https://swiperjs.com/vue)
pinia
@nuxt
nuxi
terser
nitropack
dom7
@vueuse
unstorage

<img width="1205" alt="Screenshot 2022-10-19 at 11 27 40" src="https://user-images.githubusercontent.com/465214/196666578-e32ced16-b815-42fd-80ab-75f03f9ae25c.png">

**Reply by arb85** [reply]
Uhm, I think the error is related to [H3](https://github.com/unjs/h3)
so I think we can reduce the field to:
@nuxt
nuxi
h3

Do you have this error only on GAE or also locally with:
```bash
npm run build
```
or

```bash
npm run preview
```
?

**Reply by SleepiestAdam** [reply]
Hey @arb85 - I'm afraid npm run build works fine / as does previewing / running the build locally.
The error only seems to occur when deployed to GAE.

**Reply by SleepiestAdam** [reply]
I tried updating h3 just in case that did anything. It now uploads, but then when you make a request is hangs for about 2 minutes, then times out... The logs show lots of "waiting" while this is happening, but no useful errors:

<img width="1440" alt="Screenshot 2022-10-19 at 16 28 21" src="https://user-images.githubusercontent.com/465214/196736324-6ce57294-41eb-4469-9ccb-9fa87d9c1e18.png">

**Reply by SleepiestAdam** [reply]
I'm also getting an error "ERR_TOO_MANY_REDIRECTS" in the browser client sometimes... No idea what's causing the redirects however, seems to occur no matter what url is called.

Also tried changing the NUXT_PORT to 8081 just as it says listening on 8081 in the logs. Likewise tried changing the NUXT_HOST to '127.0.0.1' just as that was the address quoted in the logs... All still result in it timing out.

Somewhat stumped...

**Reply by SleepiestAdam** [reply]
@arb85  - So it appears the re-direct only happens when trying to access the custom domain (uses CloudFlare - possibly re-attempts?)... When accessing the app engine project url directly, it just times-out after 600 seconds / resolves to a 500 error at the end. The only error log is:

"Process terminated because the request deadline was exceeded. Please ensure that your HTTP server is listening for requests on 0.0.0.0 and on the port defined by the PORT environment variable. (Error code 123)"

The environment variables are set as suggested:

env_variables:
  NUXT_HOST: '0.0.0.0'
  NUXT_PORT: 8080
  NODE_ENV: 'production'

<img width="1440" alt="Screenshot 2022-10-21 at 12 02 55" src="https://user-images.githubusercontent.com/465214/197181465-74de8b67-03ce-4125-b2ee-594091bb4489.png">

<img width="1440" alt="Screenshot 2022-10-21 at 12 03 00" src="https://user-images.githubusercontent.com/465214/197181472-e50ff574-69c9-48c8-b074-1a4bd477ec9f.png">

**Reply by arb85** [reply]
@AssyriaGameStudio I’m sorry, but unfortunately, now I'm out, but next Monday I can try to deploy to GAE a Nuxt3 “last RC” app.
I’ll update you as soon as I can! 🤞🏻

**Reply by SleepiestAdam** [reply]
@arb85 - no worries, I really just appreciate the help at all tbh, wouldn't have even got as far as being able to get it building on the server without your help 😅!

Anyways; I've done some further experimentation... I added to the environmental variables, as the Nuxt3 documentation shows these additional ones as potential environmental variables to use (https://v3.nuxtjs.org/getting-started/deployment/) rather than NUXT_PORT/HOST:

```
env_variables:
  HOST: '0.0.0.0'
  NITRO_HOST: '0.0.0.0'
  NUXT_HOST: '0.0.0.0'
  PORT: 8080
  NITRO_PORT: 8080
  NUXT_PORT: 8080
  NODE_ENV: 'production'
```

It's still timing out, however I seem to be now getting a HTTP Status Code 103: Early Hints response when initially calling the url's now (tho it still never resolves to a loaded page)... After ~600 seconds it eventually returns the error "Process terminated because the request deadline was exceeded. Please ensure that your HTTP server is listening for requests on 0.0.0.0 and on the port defined by the PORT environment variable. (Error code 123)".
