### DISCUSSION TITLE
deploying with serverless on aws lambda

### DISCUSSION THREAD

**Discussion by huang-julien** [nuxt/nuxt#16775] [Questions]
Hi ! I ran into an issue while trying to deploy a nuxt app on AWS lambda with serverless.

here's my serverless.yml

`````yml
service: ****

useDotenv: true

provider:
    name: aws
    runtime: nodejs16.x
    stage: dev
    region: ****
    deploymentMethod: direct
    environment:
        NODE_ENV: production
    apiGateway:
        shouldStartNameWithService: true
    deploymentBucket:
        maxPreviousDeploymentArtifacts: 6

functions:
    nuxt:
        handler: packages/****/.output/server/index.handler
        events:
            - http: ANY /
            - http: ANY /{proxy+}

# Optional deployment packaging configuration
package:
    excludeDevDependencies: true
    individually: true
    patterns:
        - '!**'
        - 'packages/****/.output/**'
``````
Once deployed (with the lambda preset), i can access to the url provided by serverless/aws. However any assets, such as css, or even the js chunks cannot be loaded because i receive a 403 unknown status when requesting these file. Is there any configuration i've missed ?
