### DISCUSSION TITLE
How to use pageTransition?

### DISCUSSION THREAD

**Discussion by mihail727** [nuxt/nuxt#17974] [Questions]
How to use pageTransition inside definePageMeta?

This code is doesnt work...
`@/pages/index.vue`
```js
<script setup lang="ts">
	definePageMeta({
		pageTransition: {
			name: 'index-page',
			css: true,
		},
	});
</script>
```
```css
.index-page-enter-from {
      opacity: 0;
}
.index-page-enter-active {
      transition: all 1s;
}
```
