### DISCUSSION TITLE
GitHub Action to deploy to Azure Static Web App fails because it cannot find @nuxt/kit

### DISCUSSION THREAD

**Discussion by jeremeevans** [nuxt/nuxt#18238] [Questions] [answered]
I followed the instructions to deploy to an Azure Static Web App using GitHub Actions. When the build job runs, it errors out saying:

`[error] nuxi requires `@nuxt/kit` to be installed in your project. Try installing `nuxt3` or `@nuxt/bridge` first.`

This is my first time using GitHub Actions to deploy a Static Web App. Any insights on how get it working?

![image](https://user-images.githubusercontent.com/1747006/139139314-f98adc47-61cd-4dc8-aaf0-0ba3b3cfafa2.png)

**Comment by danielroe** [comment, marked as answer]
Related issues: https://github.com/nuxt/framework/issues/1497 and https://github.com/nuxt/framework/issues/1001. You can work around this until we address the underlying issue by (one of):

* removing your package-lock.json and running `npm install`
* using npm v7 (but this won't work for Azure SWA deploy step as I'm not sure if we can configure the npm version)
* using yarn

**Note**: Unrelated to this issue, Azure SWA is currently not working pending runtime upgrade to Node 14+.

**Reply by jeremeevans** [reply]
Cool, thank! Is there any timetable on SWA upgrading to Node 14+? For others,  I added the following to the GitHub Action yml to delete the package.json (after the checkout, included for context)

   ```
   - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Delete package-lock.json - There is an issue with Azure using an old version of node 😭
        run: rm package-lock.json
```
