### DISCUSSION TITLE
Nuxt 3 - `fetch failed ()` on server-side on production

### DISCUSSION THREAD

**Discussion by iWatchYouFromAfar** [nuxt/nuxt#18625] [Questions]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `app`, `vite`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Unfortunately it is difficult for me to provide a link for a reproduction, but I will provide all the necessary source data.

### Describe the bug

In production, when accessing the page, I get an error:

```
fetch failed ()
```

The error occurs in this place, and only on the server-side.
```
const { data: node } = await useAsyncData('foo', () =>
  $fetch(`${baseUrl}v1/foo/bar/`, {
    method: 'POST',
    body: {
      url: 'index',
    },
  }),
);
```

If you go to another route and go back, this API call will work (I believe so, because at this time the request is made on the client side).

I found out that to call the API on the server side, you need to use the name of the container responsible for the API (usually this is the backend).

For that, I made such a composable:

```
import { useRuntimeConfig } from 'nuxt/app';

export const useApi = () => {
  const runtimeConfig = useRuntimeConfig();
  let baseUrl;

  (baseUrl = process.server
    ? runtimeConfig.public.BASE_API_URL
    : runtimeConfig.public.BASE_API_BROWSER_URL);

  return { baseUrl };
};
```

My env file for dev mode:

```
NUXT_PUBLIC_BASE_API_URL=http://app_local_backend:3001/api/
NUXT_PUBLIC_BASE_API_BROWSER_URL=http://localhost:3001/api/
```

My env data for prod mode and this is how i run my frontend on frontend docker container: 

```
NUXT_PUBLIC_BASE_API_URL=http://app_production_backend:3001/api/ NUXT_PUBLIC_BASE_API_BROWSER_URL=https://mysite.com:3001/api/ PORT=3050 node .output/server/index.mjs
```

In development mode, i get a fully working application. It doesn't matter if I navigate through routes or refresh the page. I always get data and everything works fine.

But in production, when i refresh the page or when i visit it for the first time, I get an error `fetch failed ()` and the data from the backend does not come accordingly, so my `data` is null.

I have not seen such problems in Nuxt 2. And it seems to me that for many who will meet with a similar problem, this question will be very useful.

Below I will provide my docker configs.

Guys, please help me understand what I'm doing wrong.

### Additional context

My production docker-compose yml file:

```
version: '3.7'

volumes:
  production_mongodb_data:

services:
  nginx_container:
    container_name: app_production_nginx
    image: app_production_nginx:latest
    restart: unless-stopped
    build:
      context: ./production/nginx
    links:
      - backend_container
      - frontend_container
    ports:
      - "80:80"
      - "443:443"
      - "8089:8089"
    volumes:
      - ../frontend/:/usr/share/nginx/html/mysite.com/frontend
  backend_container:
    container_name: app_production_backend
    image: app_production_backend:latest
    build:
      context: ./production/backend
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ../backend:/app/backend
    ports:
      - "3001:3001"
      - "9229:9229"
  frontend_container:
    container_name: app_production_frontend
    image: app_production_frontend:latest
    build:
      context: ./production/frontend
    volumes:
      - ../frontend:/app/frontend
    ports:
      - "3050:3050"
    restart: always
    command: "npm run preview"
```

My NGINX config:

```
upstream backend {
    server backend_container:3001;
}

upstream frontend {
    server frontend_container:3050;
}

server {
    listen 80;
    server_name mysite.com;

    location /.well-known/acme-challenge/ {
    	root /var/www/certbot;
    }

    location / {
      	#...
    }

}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2 ipv6only=on;
    server_name mysite.com;

    # SSL certs here

   location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass http://frontend;
        proxy_ssl_session_reuse off;
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        proxy_redirect off;
    }

    location /api {
        proxy_pass https://backend;
    }
}
```

My Frontend Dockerfile:

```
FROM node:18-alpine

WORKDIR /app/frontend

EXPOSE 3050
```
