### DISCUSSION TITLE
Include SCSS source files in module build

### DISCUSSION THREAD

**Discussion by edgarsn** [nuxt/nuxt#20546] [Questions] [answered]
Hi!

First I want to say thank you for making Nuxt so great and developer friendly. 

I'm trying to develop module which contains few pages & components. Also this module exposes source SCSS files to be able to override variables & other styles from developer\`s nuxt, but running `pnpm prepack` doesn't include those SCSS files in build.

**In module:**
`src/assets/styles/_main.scss`

```scss
$my-component-text-color: #ff0000;

.my-component {
   color: $my-component-text-color;
}
```

**Nuxt:**
`assets/styles/app.scss`

```scss
@import "@my-org/my-module/dist/runtime/assets/main";
```

But of course it doesn't import anything, because `assets` directory doesn't exist in `node_modules/@my-org/my-module/dist/runtime/` directory.

Is there any hook or nuxt kit function to force include SCSS source files in build?
