### DISCUSSION TITLE
Preload Assets with head doesnt'work

### DISCUSSION THREAD

**Discussion by luca-smartpricing** [nuxt/nuxt#20780] [Questions]
Hi guys. This line of code doesn't work 
How can i access the `asset` folder from `nuxt.config`?

```js
export default defineNuxtConfig({
    app: {
      head: {
        link: [
          {
            key: 'preload-font-family-inter',
            rel: 'preload',
            href: '/assets/fonts/Inter.woff2',
            as: 'font',
            type: 'font/woff2'
          }
       ]
    }
  },
})
```

Even in App.vue doesn't work (no, neither `@/assets/fonts/Inter.woff2`, `/assets/fonts/Inter.woff2`, `assets/fonts/Inter.woff2`)

```js
<script setup>
useHead({
  link: {
    key: 'preload-font-family-inter',
    rel: 'preload',
    href: '~/assets/fonts/Inter.woff2',
    as: 'font',
    type: 'font/woff2'
  }
})
</script>
```

**Comment by Haythamasalama** [comment]
1- You can define them in your CSS or SCS using `@font-face," which should work.

```css
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 400;
  src: url('~/assets/fonts/Inter.woff2') format('woff2');
}
```

2- Or add the fonts file in the `public` folder, not the `assets` folder.

The public folder should be like this :
```
--| public 
----| fonts
-------| Inter.woff2
```

```ts
export default defineNuxtConfig({
    app: {
      head: {
        link: [
          {
            key: 'preload-font-family-inter',
            rel: 'preload',
            href: '/fonts/Inter.woff2',
            as: 'font',
            type: 'font/woff2'
          }
       ]
    }
  },
})
```

**Reply by luca-smartpricing** [reply]
Oh, of course i can move `/font` in `/public` but as they advise in every documentation  i have `/font` in `/assets`. Seriously there's no way to preload or point an `/assets` file from `useHead()`?  
`~assets/fonts` alias work everywhere except for `useHead()`?

**Reply by Haythamasalama** [reply]
> Oh, of course i can move `/font` in `/public` but as they advise in every documentation  i have `/font` in `/assets`. Seriously there's no way to preload or point an `/assets` file from `useHead()`?  
> 
> `~assets/fonts` alias work everywhere except for `useHead()`?

Ok, you keep it in the assets folder but you should define them in css or scss folder like this you don't need useHead()

```css
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 400;
  src: url('~/assets/fonts/Inter.woff2') format('woff2');
}
```
