### DISCUSSION TITLE
Setting Up Docker-Compose in Debug Mode for Visual Studio Code

### DISCUSSION THREAD

**Discussion by MilkoEmanuilov** [nuxt/nuxt#23058] [Questions]
I have a docker-compose file that ties together four different projects, and I want to run and debug them all at once using docker-compose.

I have a few questions about the best practices for debugging locally in Visual Studio Code. Here is the setup I currently have:

docker-compose.yml file
```nuxt_service:
  build:
    context: .\CleanArchitecture.WebClient\
    dockerfile: Dockerfile
  ports:
    - "${NUXT_SERVICE_PORT}:3000"
```
Dockerfile
```
FROM node:16-alpine

WORKDIR /app

COPY package*.json ./
COPY . .

RUN npm run dev
```

This one does not work and i've tried a lot of things to make it run but probably my solution is not the correct solution.

I'm wondering if this is the right way to go about debugging the application locally or if I should stick to using the npx nuxt dev command directly in the console each time.

I want my local environment to be as closest to the production one.

Does anyone have experience with this or suggestions on which method might be better? Any advice or tips would be much appreciated!

**Comment by binochoi** [comment]
maybe u should to replace
`RUN npm run dev`
`CMD npm run dev`

**Comment by MilkoEmanuilov** [comment]
I've made it work particularly but hot reload does't work.

That's my docker-compose
```
  nuxt_service:
    volumes:
      - .\WebClient\:/app
      - /app/node_modules
    build:
      context: .\WebClient\
      dockerfile: Dockerfile
    ports:
      - "${NUXT_SERVICE_PORT}:3000"
      - 24678:24678
```

And my dockerfile.

```
FROM node:16-alpine

ENV HOST=0.0.0.0

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

CMD ["npm", "run", "dev"]
```
WS is connected and files are updated properly.

![Screenshot_51](https://github.com/nuxt/nuxt/assets/5627003/19a1c473-6a4c-4534-a5c5-9446ae245632)
![Screenshot_50](https://github.com/nuxt/nuxt/assets/5627003/ad30373c-b69d-4847-84ef-c42447b403d2)

Any suggestions why hot reload not working?
