### DISCUSSION TITLE
Pre-rendered route doesn't use correct fonts

### DISCUSSION THREAD

**Discussion by belfortf** [nuxt/nuxt#23490] [Questions]
Hi, I'm pre-rendering my landing page by doing:

``` javascript 
routeRules: {
    '/': { prerender: true },
},
```
In the project, I have a custom-fonts.css file:

```css
@font-face {
    font-family: 'Font1';
    src: url('/Font1-Bold.ttf') format('truetype');
    font-weight: 700;
    font-style: normal;
    font-display: swap;
}
```

The pre-rendered route ignores the font-face, I mean, it still says font-family Font1 but the font files are not used / downloaded. The font files are in the public directory. If I don't pre-render the page everything works fine.

Am I doing something wrong or is this a bug ? Thank you.
