### DISCUSSION TITLE
Nuxt3: Strapi Content not Updating on Production Server

### DISCUSSION THREAD

**Discussion by Nirwana3301** [nuxt/nuxt#24165] [Questions] [answered]
I am currently working on a site (mbmobilesauna.de) with Nuxt3 in the frontend. My backend is Strapi CMS. Both sites are actively running actually well in prod and dev. Side note: I've only been involved with Nuxt for a few months.

**My problem:**

I maintain the content of my site ([mbmobilesauna.de](https://mbmobilesauna.de/)) with Strapi. If I now change content in Strapi, this should then also update the website. This works so far but ONLY on localhost and not on the actual production URL.

My two sites (frontend, backend) are hosted at a service provider that uses Cloudflare. This service provider has assured me 100% that the problem is not with Cloudflare. Cloudflare caches the page only 4 hours and after the 4 hours the content should change but unfortunately this is not the case.

For my frontend project I have a Dockerfile and a Deployment.yaml which automatically publish my project as soon as I commit something new. To exclude that this is the reason, I have also tested all locally in a Docker container. Here the desired behavior is there. As soon as I change something in Strapi, the page that is in the Docker container is updated directly.

To exclude the possibility that this is a bug in Strapi, I used the Strapi prodction URL in the local development environment.

As already mentioned, everything works as it should perfectly on localhost. But as soon as the page is in production, the content is no longer updated unless I manually make a release in the frontend pipeline. (This behavior is not desired)

**What I tried:**

Try another hosting provider (Netlify, Firebase) - Here I have the same problem again in Production.

Try different browsers (Chrome, Firefox, Opera) - Again the same problem

Deactivate cache - Again the same problem

Clear cache completely - Again the same problem

How do I get my data out of Strapi:

nuxt.config.ts

```ts
  apollo: {
    clients: {
      default: {
        httpEndpoint: `https://STRAPI_PROD_URL/graphql`,
        browserHttpEndpoint: `https://STRAPI_PROD_URL/graphql`,
        connectToDevTools: false,
      },
    },
  },
```

index.vue

```ts
import gql from "graphql-tag";

const GET_HOMEPAGE = gql`
  query Homepage {
    homepage {
      data {
        id
        attributes {
          body {
            __typename
            ... on ComponentContentTypeCtLandingSection {
              id
              title
              landingDesc: description
              images {
                data {
                  id
                  attributes {
                    url
                    alternativeText
                  }
                }
              }
              link {
                id
                label
                url
                style
                unterseiten {
                  data {
                    id
                    attributes {
                      title
                      slug
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
`;

const { data }: any = await useAsyncQuery({
  query: GET_HOMEPAGE,
  cache: false
});
```

**I use for my requests NuxtApollo (https://apollo.nuxtjs.org/) and GraphQL**

**I have provided my complete repo here for more details:**
https://github.com/Nirwana3301/SaunaFrontendNuxtStackoverflow

Can anyone help me?

**Comment by danielroe** [comment]
If you find that the local build + Docker container is exhibiting correct behaviour, then the odds of this being a Nuxt issue are very minimal. Instead it is much more likely to be an issue with your deployment setup. 

Are you statically generating your site? If so, this is the expected behaviour unless you disable `experimental.payloadExtraction`.

Are you providing all the runtime environment variables that may be required?

**Reply by Nirwana3301** [reply]
Hello,

no my site is not static. Its dynamic. Here is my Dockerfile and deployment file:

Dockerfile
```dockerfile
# build stage frontend
FROM node:18.16.0-alpine as build-stage-frontend
WORKDIR /frontend
COPY mb-sauna-website .


ARG STRAPI_URL

ENV VITE_VUE_APP_STRAPI_API_URL=$STRAPI_URL

RUN npm install
RUN npm run build

# Production stage
FROM node:18.16.0-alpine

WORKDIR /app

COPY --from=build-stage-frontend /frontend/.output /app

ARG STRAPI_URL

ENV VITE_VUE_APP_STRAPI_API_URL=$STRAPI_URL

ENV NODE_ENV=production

CMD node ./server/index.mjs
```

Thats my pipeline
```yml
options:
  docker: true

definitions:
  services:
    docker:
      memory: 3072

pipelines:
  branches:
    master:
      - step:
          name: Build - Push - Deploy
          caches:
            - docker
          deployment: production
          script:
            # set image name
            - export IMAGE_NAME=registry.NAME.de/mb-sauna/website:latest

            # Docker Login
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD registry.NAME.de

            # Build image
            - docker build -t $IMAGE_NAME --build-arg STRAPI_URL=$STRAPI_URL .

            # push image
            - docker push $IMAGE_NAME

            # deploy to server
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: 'USERNAME'
                SERVER: 'vserver.NAME.de'
                COMMAND: '/home/mb-sauna/deploy.sh'
    develop:
      - step:
          name: Build - Push - Deploy (Development)
          caches:
            - docker
          deployment: staging
          script:
            # set image name
            - export IMAGE_NAME=registry.NAME.de/mb-sauna/website:dev

            # Docker Login
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD registry.NAME.de

            # Build image
            - docker build -t $IMAGE_NAME --build-arg STRAPI_URL=$STRAPI_URL_DEV .

            # Push image
            - docker push $IMAGE_NAME

            # deploy to server
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: 'USERNAME'
                SERVER: 'vserver.NAME.de'
                COMMAND: '/home/mb-sauna/dev/deploy.sh'
```

"Are you providing all the runtime environment variables that may be required?"
Yes, I do. If not, my page would not be displayed in production and the build would not go through. And the console is not showing any errors. In backend and frontend. Everything seems to be fine.
