### DISCUSSION TITLE
How to preload a local font with useHead?

### DISCUSSION THREAD

**Discussion by dbzx10299** [nuxt/nuxt#24849] [Questions] [answered]
I have a font that I downloaded from geist font, and I have a `.woff2` file.

In my main.css I have this code which is working just fine,

```css
@font-face {
  font-family: 'Geist';
  src: url(~/assets/fonts/Geist-Regular.woff2) format('woff2');
  font-weight: 400;
  font-style: normal;
  font-display: swap;
}
```
But for some reason I cannot preload it, and I have seen online this code and I still tried it and I can't get it to work. In my `app.vue` file:
```js
useHead({
  link: [
    {
      rel: 'preload',
      type: 'font/woff2',
      href: '~/assets/fonts/Geist-Regular.woff2',
      as: 'font',
      crossorigin: true
    }
  ]
})
```

This gives me an error in the terminal
```
[Vue Router warn]: No match found for location with path "/~assets/fonts/Geist-Regular.woff2"
```

On the front end it shows this error
```
GET http://localhost:3000/~/assets/fonts/Geist-Regular.woff2 net::ERR_ABORTED 404 (Page not found: /~/assets/fonts/Geist-Regular.woff2)
```
