### DISCUSSION TITLE
Please help me understand how runtimeConfig values are overridden.

### DISCUSSION THREAD

**Discussion by sregdorr** [nuxt/nuxt#27406] [Questions]
Hello Everyone! Thanks for your work on this framework. Please forgive me if this is already addressed somewhere, but I seem to be missing something that I can't find good answers for. In fact, I'm beginning to wonder if this is even an Nuxt issue and not some kind of peculiarity with node...

Why is it that after I run a `nuxt build` and then load env variables using `source .env` and then run `node .output/server/index.mjs` the runtimeConfig variables are empty. I can check that the variable was loaded correctly by outputting `echo $NUXT_KEYCLOAK_ISSUER` and seeing the correct value, but using `const { keycloak } = useRuntimeConfig()`, `keycloak.issuer` is an empty string. If I use `nuxt preview` instead, everything works just fine. If I run it with `NUXT_KEYCLOAK_ISSUER=**** node .output/server/index.mjs` it seems to load the runtimeConfig that way as well.

How I ran across this was in my docker build. I build the docker image for production from this Dockerfile:
```
FROM node:20-buster as builder
WORKDIR /build

COPY ./package.json /
COPY ./package-lock.json /

RUN npm ci

COPY . .

ARG GIT_COMMIT
ARG APP_VERSION

ENV NUXT_GIT_COMMIT_HASH=$GIT_COMMIT
ENV NUXT_APP_VERSION=$APP_VERSION
ENV NODE_ENV=production
RUN npm run build

ENV HOST 0.0.0.0
EXPOSE 3000

ENTRYPOINT ["node", ".output/server/index.mjs"]

```
Then when I try to run it from this compose file, the runtimeConfig values are empty:
```
version: "3"

services:
  myservice:
    container_name: myservice
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: "1.2.3"
        GIT_COMMIT: xx.test
    environment:
      - NUXT_AUTH_SECRET=********************
      - AUTH_ORIGIN=http://localhost:3000
      - NUXT_KEYCLOAK_CLIENT_ID=***************
      - NUXT_KEYCLOAK_CLIENT_SECRET=****************************
      - NUXT_KEYCLOAK_ISSUER=https://********************.com/realms/*****
    ports:
      - "3000:3000"

```

Can you help me understand what I'm doing wrong?
