### DISCUSSION TITLE
How to add css variable with v-bind at nuxt pages/index

### DISCUSSION THREAD

**Discussion by XY-ShadowK** [nuxt/nuxt#30677] [Questions] [answered]
I am migrating my vue3 project to nuxt3, but I found that the main page at `pages/index.vue` is not the root page which also mounts when any page is active.
In my vue project, I use `app.vue` to add dynamic css variable with v-bind and classes uses them.
So how can I let them run globally in nuxt as they did in my vue project? Or should I use `app.vue` in company with `app/router.options.ts` instead of `pages/`(auto-generated router option). My vue solution is below.

```css
.page{
    --main-bg-color: v-bind('theme.list.mainColor');
    --second-bg-color: v-bind('theme.list.secondColor');
    --accent0-bg-color: v-bind('theme.list.accentColor[0]');
    --accent1-bg-color: v-bind('theme.list.accentColor[1]');
    --main-font-color: v-bind('theme.list.mainFontColor');
    --second-font-color: v-bind('theme.list.secondFontColor');
    --main-button-color: v-bind('theme.list.buttonColor');
    --main-button-hover-color: v-bind('theme.list.buttonHoverColor');
    background-color: var(--main-bg-color);
}
```
