### DISCUSSION TITLE
SSR with AWS Amplify

### DISCUSSION THREAD

**Discussion by tetz2442** [nuxt/nuxt#8249] [Questions (Nuxt 2)]
Has anyone tried setting up Nuxt on AWS Amplify with server side rendering enabled? It was simple to get the static generation up and running, but I'm having more trouble with SSR. All the examples I've found have been for Next.js

My current amplify.yml for SSG
```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn generate
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
  customHeaders:
    - pattern: '**/*'
      headers:
      - key: 'Cache-Control'
        value: 'public, max-age=31536000, immutable'
```
