### DISCUSSION TITLE
Nuxt fully static with circle CI

### DISCUSSION THREAD

**Discussion by gabrielsze** [nuxt/nuxt#9850] [Questions (Nuxt 2)]
Hi all, I would like to seek some advice on utilizing the nuxt fully static (skipping webpack builds - https://nuxtjs.org/announcements/nuxt-static-improvements/#generate-time-cache-vs-full-webpack-build) with circle CI, where it mentions 

"If you are using a CI, ensure that you are properly caching node_modules."

The current issue I face is that my cache doesn't seem to be saved - essentially highlighted here (https://support.circleci.com/hc/en-us/articles/360004632473-No-Cache-Found-and-Skipping-Cache-Generation). And apparently that's because the package-lock is being overwritten.

my circleci config.yml looks like this
```
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Nuxt Build to dist folder
          command: npm run generate
```

The problem is that my cache is not saving, and i think therefore I'm not reaping the benefits of the skipping webpack builds for faster builds. I have tried replacing `npm install` with `npm ci` instead (which I believe actually saves the cache), but that in turns slow down the installing of dependencies significantly.

I am wondering if anyone has managed to implement the skipping of webpack builds with circle CI and any advice on how to approach it! Thanks!
