### DISCUSSION TITLE
Preloading Fonts

### DISCUSSION THREAD

**Discussion by thomasbnt** [nuxt/nuxt#9915] [Questions (Nuxt 2)] [answered]
Hello ! I have a question, how I can preload fonts on Nuxt? I have the famous "flash" of font as soon as the talk starts to load. it doesn't even last 1 second, but it's a bit destabilizing 😶

**Comment by hsks** [comment, marked as answer]
You should add the `<link rel="preload" href="link/to/font">` either to the `head` method of the file you want to preload font in, or in `nuxt.config.js` to add it globally across the app.

**Reply by thomasbnt** [reply]
I updated my file :

```css
@font-face {
  font-family: 'Comfortaa';
  src: url("/fonts/comfortaa.ttf") format('truetype');
}
```

On my main CSS file. Seems working, thanks for your help, I just changed that locally 👍🏼
