### ISSUE TITLE
Nuxt on Github actions can't find plugin file

### ISSUE THREAD

**Issue by sts-ryan-holton** [nuxt/nuxt#10039]
### Is your feature request related to a problem? Please describe.

I'm using Github actions to run my Cypress tests on my repository, I have several plugins in my Nuxt config file, and each time the action workflow runs, I'm getting an error whereby my plugins aren't found?

> Error: Plugin not found:

My plugin is inside of `plugins/Helpers/getClasses.js` so I'm not sure why Nuxt can't find it via github actions, please advise me on what I'm doing wrong or what I need to change

My plugins array is:

```javascript
// Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
plugins: [
  { mode: 'client', src: '@/plugins/Helpers/getClasses' },
  { mode: 'client', src: '@/plugins/Helpers/sortArrayByAlphabetical' },
  { mode: 'client', src: '@/plugins/Form/Steps/Employment/employmentStatus' },
  { mode: 'client', src: '@/plugins/Form/Steps/Income/income' },
  { mode: 'client', src: '@/plugins/vue-axios' },
  { mode: 'client', src: '@/plugins/vee-validate' },
],
````

My workflow is:

```yml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          browser: chrome
          headless: true
          build: npm run generate
          start: npm run start
          wait-on: 'http://localhost:3000'
          config-file: cypress.github-actions.json
```
![Screenshot 2021-11-11 at 12 12 53](https://user-images.githubusercontent.com/25177538/141296268-27492d00-dc22-48ce-ab95-16a28a4d6948.png)
