### ISSUE TITLE
Css properties change their order in production

### ISSUE THREAD

**Issue by VladStepanov** [nuxt/nuxt#19240]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-akeqjs?file=app.vue
Steps
1. Open reproduction
2. With devtools inspect `h1`. It should be centered.
3. Stop dev server
4. `npm run build && node .output/server/index.mjs`
5. Refresh container page
6. Text inside `h1` now aligned to left
7. Inspect `h1`. All prefixed properties hoisted to top

### Describe the bug

prefixed css properties in production are always at top of class.
If we have following in our component
```css
.class {
  all: unset;
  -webkit-box-orient: vertical;
}
```
In production it would be
```css
.class {
  -webkit-box-orient: vertical;
  all: unset;
}
```

I would be grateful for any workaround because this bug breaks some styles especially with `all: unset;`
