### ISSUE TITLE
Issue with running Nuxt.js development server in Kubernetes using Okteto

### ISSUE THREAD

**Issue by tebaly** [nuxt/nuxt#20663]
### Environment

Nuxt.js development server in Kubernetes using Okteto

### Reproduction

try

```yaml
  vite: {
    server: {
      hmr: {
        host: 'localhost',
        port: 3001,
      },
    },

```
okteto

```yaml
    sync:
     - "./:/app"
    command: ["yarn", "dev", "-p", "3000", "--no-clear"]
    securityContext:
      runAsNonRoot: false
      allowPrivilegeEscalation: true
    forward:
      - localPort: 3001
        remotePort: 3001
        name: app
      - localPort: 3000
        remotePort: 3000
        name: app
      - localPort: 8000
        remotePort: 80
        name: app
```

### Describe the bug

I'm having trouble running the Nuxt.js development server in Kubernetes using Okteto. When I try to run the server, I get the following error in browser console:
client.ts:78 WebSocket connection to 'ws://localhost:3001/_nuxt/' failed: 
client.ts:324 GET http://localhost:3001/_nuxt/ net::ERR_CONNECTION_RESET

the application itself is opened locally through Okteto forwarded port 3000 - but HMR not working

### Additional context

I've tried setting the HMR port in my nuxt.config.js file, and I've also added port forwarding to my Okteto manifest file, but I'm still getting this error. My Nuxt.js version is 3.3.3.

Can someone help me figure out what's going on?

**Comment by tebaly** [comment]
```yaml
  vite: {
    ...
    server: {
      hmr: {
        port: 3001,
        timeout: 3,
        clientPort: 80,
      },
    },
  } 
```
This works in every case without HTTPS
