### ISSUE TITLE
Image are used in wrong reference in stylesheet file after build with rollup

### ISSUE THREAD

**Issue by Garfill** [nuxt/nuxt#20845]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.4.2
- Nitro Version:    2.4.0
- Package Manager:  pnpm@8.2.0
- Builder:          vite
- User Config:      app, css, modules, vite
- Runtime Modules:  @unocss/nuxt@0.51.8, nuxt-svgo@3.1.0
- Build Modules:    -
------------------------------

### Reproduction

1. Set the `rollupOptions` with `vite.build ` in nuxt.config like below
```ts
rollupOptions: {
        output: {
          assetFileNames: (assetInfo) => {
            let extType = assetInfo.name?.split('.')[1] ?? ''
            if (/(png|jpe?g|svg)$/i.test(extType)) {
              extType ='img'
            } else if (/s?css$/i.test(extType)) {
              extType = 'css'
            }
            return `_nuxt/${extType}/[name].[hash].[ext]`
          }
        }
      }
```
2. After build, there are two dirs called css and img, but the css file use some images in img dir like that

```css
.some-calss {
  background:  url('./img/a.png')
}
```
3. So the pages cannot show the background-image because 404

### Describe the bug

1. The style are built like that

```css
.some-calss {
  background:  url('./img/a.png')
}
```
2. While the expected result should like that
```css
.some-calss {
  background:  url('../img/a.png')
}
```
