### ISSUE TITLE
Nuxt 3 DevTools Overflow

### ISSUE THREAD

**Issue by ThatOneRockyBoy** [nuxt/nuxt#23061]
### Environment

Nuxt project info:                                                                                                                      12:12:23

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules, css
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0
- Build Modules:    -
------------------------------

### Reproduction

Always

### Describe the bug

When enabling dev tools and setting a background makes the page overflow.

When setting scss to this:
```scss
html,
body,
#__nuxt {
  @apply w-full h-full;
}

body {
  background-image: url('/images/background.jpg');
  @apply bg-neutral-800 bg-cover bg-center backdrop-blur-sm bg-no-repeat bg-fixed;
}

```

It overflows the page and adds a scrollbar.

![image](https://github.com/nuxt/nuxt/assets/135866417/b31569f4-60e9-435f-92c4-35c116c741cb)

I could just disable the dev tools sure but it would be nice if it didn't affect my own styling.
