### ISSUE TITLE
HMR Not Working for New Files in pages and server Directories within Docker Environment

### ISSUE THREAD

**Issue by lafllamme** [nuxt/nuxt#26180]
### Environment

**Reproduction example for the described use case (pages & api functionality):** 
https://stackblitz.com/edit/github-drgy5q?file=nuxt.config.ts

### Reproduction

**Environment**

    Nuxt Version: "nuxt": "^3.10.3",
    Docker Version: 4.28.0 (139021)
    Operating System: Windows 11 Version 10.0.22631 Build 22631, MacOS Ventura (latest official)
    

### Describe the bug

We are encountering an issue with Hot Module Replacement (HMR) within a Docker environment on both MacOS and Windows (using WSL 2.0). Specifically, the problem involves adding new files to the pages and server directories of our Nuxt 3 application. Changes to existing files, including components, styles, and text contents, are correctly recognized and processed. However, new files added for routes in pages or for APIs in server are not detected until the Docker container or the Nuxt server is restarted.

**Steps to Reproduce**

1.     Start the Nuxt application in a Docker container.
2.     Add a new file to the pages directory to create a new route.
3.     Attempt to access the new route or wait for HMR to detect the change.
4.     Repeat steps for adding a new file in the server directory for an API.

Expected Outcome: Changes or new files should be recognized by HMR and applied immediately.

Actual Outcome: New files are only recognized and processed after restarting the Docker container or Nuxt server.

Potential Causes

It appears that the HMR configuration or Docker settings may not be correctly set up to detect new files in the filesystem. The issue could be related to the watch configuration or specific settings for Docker environments that affect filesystem change detection.
Attempted Solutions

-     Enabled polling in the Vite configuration (as shown in the provided code snippet).
-     Tried various host and HMR settings.

Unfortunately, these approaches did not resolve the issue.
    
This is my docker-compose.yml (lies at same-root level):
```

version: '3.8'
services:
  anime-app-nuxt:
    image: oven/bun:latest # The image name
    container_name: anime-app-nuxt
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - .:/app
    working_dir: /app # Set working directory to where your app is
    restart: always
    command: sh -c "bun install && bun run dev"
    environment: # Correct command to install dependencies and run dev server    environment:
      - NODE_ENV=development
    user: bun
```

This is corresponding nuxt.config.ts with adjustments for local dev server (page / server changes not reflecting):
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
    modules: [
        '@unocss/nuxt'
    ],
    devtools: {
        enabled: true,

        timeline: {
            enabled: true
        }
    },
    app: {
        pageTransition: {
            name: 'page',
            mode: 'out-in'
        }
    },
    //pages: true,
    //fix issue for docker not reflecting changes
    vite: {
        server: {
            host: '0.0.0.0',
            hmr: {
                protocol: 'ws',
                host: 'localhost'
            },
           /* client: {
                webSocketURL: 'ws://0.0.0.0:8080/ws',
            },*/
            watch: {
                usePolling: true,
                interval: 1000,
            },
        },
    },
})
```

**Comment by lafllamme** [comment]
This issue might be related to this issue here:


https://github.com/nuxt/nuxt/issues/23219


I still face the issue, that inside docker, regardless of package manager and os, changes under /server are not reflected.

**Comment by Dino-Kupinic** [comment]
I had this issue months ago and gave up nuxt+docker
issues with nuxt/pinia+docker aswell

**Comment by KirVelikiyy** [comment]
hi all! 
if somebody still have this error, you can try this config. 
```typescript
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  vite: {
    server: {
      watch: {
        usePolling: true,
        interval: 300 // ms
      }
    }
  },
})
```

also i used docker-compose.yaml
```yaml
version: '3.8'
services:
  client:
    build:
      context: .
    container_name: client_frontend
    command: 'npm run dev'
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
```

with Dockerfile
```dockerfile
FROM node:22-alpine
COPY package.json .
RUN npm config set registry https://registry.npmjs.org/
RUN npm i
WORKDIR /app
```

hope it will work

**Comment by Macawls** [comment]
After a lot of trial and error 😅 I got it working on windows with the following ->

**System**
- Bun: 1.1.8
- Nuxt: 3.13.0
- Docker: 24.0.7
- Windows: 10.0.19045 N/A Build 19045

docker-compose.yml
```yml
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 24678:24678 # vite hmr
    restart: unless-stopped
    volumes:
      - ./app:/app
      - /app/node_modules
```
Dockerfile.dev

```Dockerfile
FROM oven/bun:1 as base

WORKDIR /app
ENV NODE_ENV=development

FROM base as build
COPY package*.json bun.lockb ./
RUN bun install

FROM base
COPY --from=build /app/node_modules /app/node_modules

EXPOSE 3000

ENV CHOKIDAR_USEPOLLING=true
CMD ["bun", "run", "dev", "--host", "0.0.0.0"]
````

Nuxt Config
```js
$development: {
  vite: {
    server: {
      watch: {
        usePolling: true,
      },
      hmr: {
        protocol: "ws",
        host: "0.0.0.0",
        port: 24678,
      },
    },
  },
},
```
