### ISSUE TITLE
Warnings at build time [x] referenced in [y] didn't resolve at build time, it will remain unchanged to be resolved at runtime

### ISSUE THREAD

**Issue by Predota** [nuxt/nuxt#26379]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.0
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, css
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-mrq86l-s2dqph

### Describe the bug

After upgrading to 3.11, the build log is filled with messages like:

> [x] referenced in [y] didn't resolve at build time, it will remain unchanged to be resolved at runtime

This is introduced when using images from the public folder in styles.

There is two examples in my reproduction, one in `main.css` and one in the `style` tag of `app.vue`.

Running `npm run build` or `npm run generate` will produce the warnings when building the client and the server.

**Comment by HigherOrderLogic** [comment]
Changing to `url('~/public/favicon.ico')` does the trick.

And shouldn't it be this way to refer to local assets/public file?

**Comment by Tristan971** [comment]
> Changing to url('~/public/favicon.ico') does the trick.

No it doesn't really do the trick. Because this results in the static file being copied as an asset.

Which means that:
- it doesn't benefit from proper browser caching afterwards, because of the hashing
- gets needlessly preloaded as if it was a critical part of the application

We're having this issue with our font faces, ie this:

```css
@font-face {
  font-display: swap;
  font-family: "Poppins";
  font-style: normal;
  font-weight: 100;
  src:
    url("/fonts/poppins/poppins-v19-100.woff2") format("woff2"),
    url("/fonts/poppins/poppins-v19-100.woff") format("woff");
}

@font-face {
  font-display: swap;
  font-family: "Poppins";
  font-style: normal;
  font-weight: 300;
  src:
    url("/fonts/poppins/poppins-v19-300.woff2") format("woff2"),
    url("/fonts/poppins/poppins-v19-300.woff") format("woff");
}

[...]
```

This will then end up inside the manifest and all other places where we then have to specifically remove it from. And we still lose caching.
