### ISSUE TITLE
CSS being carried away from a layout into other pages that don't use that layout

### ISSUE THREAD

**Issue by adamcole123** [nuxt/nuxt#29296]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      build, site, app, colorMode, compatibilityDate, devtools, modules, serverMiddleware, auth
- Runtime Modules:  @sidebase/nuxt-auth@0.8.1, @nuxt/ui@2.18.4, @nuxtjs/seo@2.0.0-rc.23 
- Build Modules:    -

### Reproduction

I am using a layout that is specifically for the login page of my app. This is because I want the page to take up the entire screen (remove the navbar etc.).

An issue im having is that the CSS that im using to remove the body margin and whatever is being carried back out of the login screen and into the rest of the app

Here's the CSS in the layout:
```css
<style>
body, html {
  margin: 0;
  padding: 0;
  height: 100%;
}
.login-layout {
  height: 100%;
  min-height: 100%;
}
.app-wrapper {
  height: 100%;
  min-height: 100%;
  padding: 0px;
  min-width: 100%;
}
#__nuxt {
  height: 100%;
  min-height: 100%;
}
</style>
```

### Describe the bug

`.app-wrapper` is applied to the body etc. so that when I go to the login screen it just applies those styles.

When I go back to `/` for example, the `.app-wrapper` style is still applied to the page, and so the body loses its margin etc. that it had originally.

How can I fix this?
