### ISSUE TITLE
Dockerfile env variables don't override runtimeConfig using Github Actions

### ISSUE THREAD

**Issue by s-blanar** [nuxt/nuxt#30605]
### Environment

- Operating System: Linux
- Node Version:     v22.13.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.20.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.15.4
- Builder:          -
- User Config:      future, app, vite, devServer, components, site, routeRules, modules, image, gtag, i18n, tailwindcss, icon, primevue, runtimeConfig, devtools, compatibilityDate
- Runtime Modules:  @nuxtjs/i18n@8.5.6, @nuxtjs/tailwindcss@6.13.1, @nuxt/image@1.9.0, nuxt-gtag@3.0.2, @vueuse/nuxt@12.4.0, @nuxtjs/seo@2.0.3, nuxt-primevue@3.0.0, @nuxt/eslint@0.7.5, @nuxt/icon@1.10.3, @nuxt/fonts@0.10.3, @pinia/nuxt@0.9.0
- Build Modules:    -

### Reproduction

Complicated to reproduce as it happens in github actions and docker.

### Describe the bug

Hi guys, 
I am building my app with Github Actions and in my repo I have set two env variables "NUXT_PUBLIC_BACKEND_URL_INT" and "NUXT_PUBLIC_BACKEND_URL_EXT", but they are not overridden and stay empty strings in runtime.
Docker build step in my workflow yaml looks like this:
``` yaml
        env:
            REPO_ID: *****
            NUXT_PUBLIC_BACKEND_URL_INT: ${{ vars.NUXT_PUBLIC_BACKEND_URL_INT }}
            NUXT_PUBLIC_BACKEND_URL_EXT: ${{ vars.NUXT_PUBLIC_BACKEND_URL_EXT }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Get BUILD_SHA
              run: echo "BUILD_SHA=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV

            - name: Build Docker image
              run: docker build --build-arg "NUXT_PUBLIC_BACKEND_URL_INT=$NUXT_PUBLIC_BACKEND_URL_INT" --build-arg "NUXT_PUBLIC_BACKEND_URL_EXT=$NUXT_PUBLIC_BACKEND_URL_EXT" -t cr4uhra3fp9d.azurecr.io/$REPO_ID:$BUILD_SHA .
```

Then in my Dockerfile, it looks like this:
``` Dockerfile
FROM node:22-slim AS build

ARG NUXT_PUBLIC_BACKEND_URL_INT
ARG NUXT_PUBLIC_BACKEND_URL_EXT

# Enable pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY ./package.json /app/

RUN pnpm install --shamefully-hoist

COPY . ./

ENV NODE_OPTIONS="--max-old-space-size=4096"

ENV NUXT_PUBLIC_BACKEND_URL_INT=$NUXT_PUBLIC_BACKEND_URL_INT
ENV NUXT_PUBLIC_BACKEND_URL_EXT=$NUXT_PUBLIC_BACKEND_URL_EXT

RUN pnpm run build

# --------------------

FROM node:22-slim

WORKDIR /app

COPY --from=build /app/.output ./

ENV NUXT_PUBLIC_BACKEND_URL_INT=$NUXT_PUBLIC_BACKEND_URL_INT
ENV NUXT_PUBLIC_BACKEND_URL_EXT=$NUXT_PUBLIC_BACKEND_URL_EXT

EXPOSE 3000
CMD ["node", "/app/server/index.mjs"]

```

and lastly nuxt.config.ts:
```ts
runtimeConfig: {
      public: {
          backendUrlExt: "",
          backendUrlInt: "",
      },
  },
```

I am deploying my app to MS Azure kubernetes cluster. When I have these env variables set in my local environment in .env file, it works correctly and also if I use Vercel and have them set in project environment variables. I also tried creating .env file directly inside Dockerfile (without success) like this:
``` Dockerfile
RUN cat <<EOF >> .env
  NUXT_PUBLIC_BACKEND_URL_INT=$NUXT_PUBLIC_BACKEND_URL_INT
  NUXT_PUBLIC_BACKEND_URL_EXT=$NUXT_PUBLIC_BACKEND_URL_EXT
EOF

RUN pnpm run build
```

### Logs

```shell-script

```
