### ISSUE TITLE
After Nuxt version update, virtual file system URL encoding causes 404 errors when accessing app through Apache proxy

### ISSUE THREAD

**Issue by mocsimas** [nuxt/nuxt#30811]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v20.11.1`
- Nuxt Version:     `3.15.4`
- CLI Version:      `3.21.1`
- Nitro Version:    `2.10.4`
- Package Manager:  `npm@10.2.4`
- Builder:          `-`
- User Config:      `debug`, `dev`, `app`, `devtools`, `ssr`, `security`, `runtimeConfig`, `build`, `modules`, `imports`, `plugins`, `css`, `alias`, `routeRules`, `server`, `devServer`, `vite`, `compatibilityDate`
- Runtime Modules:  `@pinia/nuxt@0.9.0`, `@nuxtjs/tailwindcss@6.13.1`, `@vueuse/nuxt@12.5.0`, `dayjs-nuxt@2.1.11`, `nuxt-security@2.1.5`
- Build Modules:    `-`
- Apache Version: `2.4.51`

### Reproduction

https://codesandbox.io/p/devbox/compassionate-stonebraker-8n354r

### Describe the bug

After updating from Nuxt 3.13.2 to Nuxt 3.15.4, my application started to receive 404 HTTP statuses from Nuxt related requests which are initiated by https://my-project.local/_nuxt/C:/wamp64/www/my-project/frontend/node_modules/nuxt/dist/app/entry.js:
![Image](https://github.com/user-attachments/assets/edbc981f-ab41-477c-8559-a016ccd02131)

I've noticed that after Nuxt version update, it started to URL encode some of virtual file system files URLs, f.e. from: 
https://my-project.local/_nuxt/@id/virtual:nuxt:C:/wamp64/www/my-project/frontend/.nuxt/fetch.mjs
before the update, to:
https://my-project.local/_nuxt/@id/virtual:nuxt:C%3A%2Fwamp64%2Fwww%2Fmy-project%2Ffrontend%2F.nuxt%2Ffetch.mjs
after the update.

If I access my application through _https://localhost:3000_, all of Nuxt related requests returns expected 200 HTTP status and there are no issues. But when I run my application through Apache reverse proxy - accessing my application through _https://my-project.local_ which then proxies to _https://localhost:3000_, it can't resolve Nuxt necessary requests (see image above) and responds with 404 status.

I've added `AllowEncodedSlashes NoDecode` to my project Apache vhost configuration and it solves the issue, but it poses security vulnerabilities, so I want to avoid it. Is there any way I could make my Nuxt application avoid URL encoding or is it a requirement from now on?

Thank you!

### Additional context

I wanted to find the causer of the problem, so I did some digging at `/node_modules/nuxt/dist/shared/nuxt.CElo1U5K.mjs`. Found a `VirtualFSPlugin `which I tried to mock. Inside it I removed _encodeURIComponent_ function calls and it stopped to URL encode virtual files URLs and it started to work. I know that this is not a solution - no comments needed about what I did here.

### Logs

```shell-script

```

**Comment by thomashohn** [comment]
Can confirm that the "work-around" fixes the issue for me too

**Comment by ayalon** [comment]
I have the same issue. Took me hours to get here.

**Comment by meirhlmn** [comment]
Same. Workaround to add: AllowEncodedSlashes NoDecode to apache conf seems to work.

**Comment by giovannimanzoni** [comment]
So @danielroe what is the solution for Nginx as reverse proxy ? I tried different solutions but nothing work.

**Comment by giovannimanzoni** [comment]
I can confirm that use Apache with AllowEncodedSlashes NoDecode rule, let me work and see the website correctly.

But it is absurd that the development with Nginx is broken and that a solution was not found before applying this patch, by experienced people like you

**Comment by giovannimanzoni** [comment]
I can now say that the problem has disappeared. I can work with Nginx again as if nothing had happened.

**Comment by danielroe** [comment]
I'm pleased to hear it ❤

**Comment by ckhatton** [comment]
For anyone stumbling across this, in your Apache config add this to the Directory or Location (when virtual host proxy forwarding) block:

```apache
<Directory /var/www/example.com/public_html>
    AllowEncodedSlashes NoDecode
    # Other directives...
</Directory>

# OR

<Location />
    AllowEncodedSlashes NoDecode
    # Other directives...
</Location>
```

**Comment by Briareos17** [comment]
Confirmed same issue with Traefik, nuxt config: 
```
import { fileURLToPath } from "node:url";
import Aura from '@primeuix/themes/aura';
import tailwindcss from '@tailwindcss/vite';

export default defineNuxtConfig({
    compatibilityDate: '2025-07-15',
    devtools: {enabled: false},
    ssr: false,
    alias: {
        '@': fileURLToPath(new URL('./', import.meta.url))
    },
    vite: {
        plugins: [tailwindcss()],
        server: {
            hmr: {
                protocol: 'wss',
                clientPort: 443,
                host: 'appointo.localhost'
            },
            allowedHosts: [
                'appointo.localhost',
                '.appointo.localhost'
            ]
        }
    },
    devServer: {
        host: '0.0.0.0',
        port: 3000
    },
    modules: [
        '@nuxt/eslint',
        '@pinia/nuxt',
        'nuxt-auth-sanctum',
        '@nuxtjs/i18n',
        '@primevue/nuxt-module',
        'pinia-plugin-persistedstate/nuxt',
    ],
    primevue: {
        options: {
            theme: {
                preset: Aura,
                options: {
                    darkModeSelector: '.dark',
                    cssLayer: false
                }
            }
        }
    },
    css: [
        'primeicons/primeicons.css',
        '~/assets/css/main.css',
    ],
    i18n: {
        locales: [
            { code: 'uk', language: 'uk-UA', file: 'uk.json' },
            { code: 'en', language: 'en-US', file: 'en.json' }
        ],
        defaultLocale: 'uk',
        lazy: true,
        langDir: 'locales/',
        strategy: 'no_prefix'
    },

    runtimeConfig: {
        public: {
            auth: {
                baseUrl: process.env.NUXT_API_BASE_URL || 'http://localhost:8000'
            }
        }
    },
    components: true,
    imports: {
        dirs: [
            '~/composables',
            '~/composables/*/index.{ts,js,mjs,mts}',
            '~/composables/**',
            '~/utils',
            '~/utils/**',
            '~/stores',
        ]
    },
    sanctum: {
        baseUrl: process.env.NUXT_API_BASE_URL,
        mode: 'cookie',
        redirect: {
            home: '/',
            login: '/login',
        },
        endpoints: {
            user: '/me'
        },
        globalMiddleware: {
            enabled: false
        }
    },
    plugins: [
        '~/plugins/v-can.ts',
        '~/plugins/theme.client.ts'
    ],
    // Ignore SSL certificate errors for self-signed certificates in local environment
    $development: {
        nitro: {
            experimental: {
                nodeFetchOptions: {
                    rejectUnauthorized: false
                }
            }
        }
    }

})
```

**Comment by danielroe** [comment]
@Briareos17 this isn't an issue with nuxt/vite - you need to configure your reverse proxy not to decode encoded paths

**Comment by gioscarda** [comment]
@Briareos17, with Traefik (v3.6.6) all encoded character filtering is enabled by default (https://doc.traefik.io/traefik/security/request-path/#encoded-character-filtering). Being just for development, I solved the issue by disabling all those filters.

Example with Docker compose:
```
services:

  traefik_proxy:
    env_file:
      - .env.local
    image: traefik:latest
    restart: unless-stopped
    command:
      - --log.level=WARN
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
      - --entryPoints.web.forwardedHeaders.insecure=true
      # Encoded character filtering disabled !!!
      - --entryPoints.web.http.encodedCharacters.allowEncodedSlash=true
      - --entryPoints.web.http.encodedCharacters.allowEncodedBackSlash=true
      - --entryPoints.web.http.encodedCharacters.allowEncodedNullCharacter=true
      - --entryPoints.web.http.encodedCharacters.allowEncodedSemicolon=true
      - --entryPoints.web.http.encodedCharacters.allowEncodedPercent=true
      - --entryPoints.web.http.encodedCharacters.allowEncodedQuestionMark=true
      - --entryPoints.web.http.encodedCharacters.allowEncodedHash=true
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

Hope it helps :)
