### ISSUE TITLE
Nuxt build breaks CSS with when using `@media (width <= theme('screen.lg'))`

### ISSUE THREAD

**Issue by AntonyZ89** [nuxt/nuxt#31742]
### Environment

- Operating System: `Linux`
- Node Version:     `v20.17.0`
- Nuxt Version:     `3.16.2`
- CLI Version:      `3.24.1`
- Nitro Version:    `2.11.8`
- Package Manager:  `npm@10.8.2`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`, `css`, `modules`, `fonts`, `vite`
- Runtime Modules:  `@nuxt/fonts@0.11.1`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/p/devbox/autumn-snow-pgtnw9

### Describe the bug

I have the following CSS used in `components/Logo.vue`:

```css
.logo {
  --stroke: var(--width-md);

  &.full-stroke {
    .logo-g,
    .logo-y,
    .logo-w {
      letter-spacing: var(--tracking-wide);

      text-shadow:
        calc(1px * -1) var(--stroke) var(--color),
        calc(1px * -1) calc(1px * -1) var(--color),
        var(--stroke) calc(1px * -1) var(--color),
        calc(1px * -1) 0px var(--color),
        0px var(--stroke) var(--color),
        var(--stroke) var(--stroke) var(--color);
    }
  }
}
```

In development mode, it loads correctly:

![Image](https://github.com/user-attachments/assets/904f7691-7a40-4556-a634-0cf1e8fb63d0)

However, after building the project, the CSS doesn't load as expected:

![Image](https://github.com/user-attachments/assets/e3aca315-92dd-4440-9dfe-43ab26f29ff2)

The issue seems to be caused by missing spaces in the compiled CSS output:

```css
.logo.full-stroke .logo-g[data-v-75e84bac],.logo.full-stroke .logo-w[data-v-75e84bac],.logo.full-stroke .logo-y[data-v-75e84bac] {
    letter-spacing: var(--tracking-wide);
/*                                                    \/ missing space */
    text-shadow: -1pxvar(--stroke)var(--color),-1px-1pxvar(--color),var(--stroke)-1pxvar(--color),-1px0px var(--color),0 var(--stroke)var(--color),var(--stroke)var(--stroke)var(--color)
/*                               /\ missing space */
}
```

As you can see, there are missing spaces between values like `-1px`, `var(--stroke)`, and `var(--color)`.

I have tested the same code using only Vue (without Nuxt), and this issue does not occur. The text-shadow with CSS variables renders correctly both in development and after build.

This suggests the problem might be related to Nuxt's build pipeline or a specific PostCSS/Vite transformation used by Nuxt.

### Logs

```shell-script

```

**Comment by atinux** [comment]
Hi @AntonyZ89 

I suspect our HTML nano to be too agressive here: https://github.com/nuxt/nuxt/blob/d33497ba6e4e821cb78a3c2b64db458ba1a32db7/packages/ui-templates/lib/render.ts#L89

But I tested locally on nuxt playground and could not reproduce your issue:

![Image](https://github.com/user-attachments/assets/d4f5b112-5aec-4709-9e4e-28ec0062294e)

But note that I am not using TailwindCSS, could you try without it to see if this issue come combined when used with TailwindCSS?

**Comment by AntonyZ89** [comment]
@atinux You were right! The problem only happens when the Tailwind CSS plugin is added to Vite, I missed testing that. Thank you for pointing it out 🙏

I'll open an issue in the Tailwind CSS plugin repository.

**Comment by AntonyZ89** [comment]
It seems that using theme() directly inside a media query might break CSS parsing or value resolution during the build process (especially when combined with other custom properties).

Causes the bug:

```css
@media (width <= theme('screens.lg')) {
  .logo {
    --stroke: var(--width);
  }
}
```

Works fine:

```css
@media (width <= var(--breakpoint-lg)) {
  .logo {
    --stroke: var(--width);
  }
}
```
