### ISSUE TITLE
Have PostCSS take into account global CSS

### ISSUE THREAD

**Issue by justintaddei** [nuxt/nuxt#6534]
### What problem does this feature solve?

Using CSS custom properties could be great, but right now it's a pain.

Consider this:

You include your global css in `nuxt.config.js`
```js
module.exports = {
    // ...
    css: ['~/assets/css/global.css`]
}
```

`global.css` looks like this:
```css
:root {
    --red: #f00;
}
```

Then in `Home.vue` you do this:

```vue
<template>
    <div>
        <h1>Home</h1>
    </div>
</template>

<style scoped>
    h1 {
        color: var(--red);
    }
</style>
```

When this is compiled the CSS output for `Home.vue` is this:
```css
h1 {
    color: var(--red);
}
```

Had the global CSS been taken into consideration the output would've been this:
```css
h1 {
    color: #f00;
    color: var(--red);
}
```

### What does the proposed changes look like?

This would appear the same on the surface, only altering the compiled CSS output.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9879">#c9879</a>)</em></sub></div>
